### ISSUE TITLE
Recovery Chroot system not listens any port

### ISSUE THREAD

**Issue by iav** [Ft1Byh0hl/spacemonkey_root#4]
I follow your script op to boot from my disk. It turns green led, then turns it blue. I seeit takes DHCP address. 
But I can't connect to ssh — connection refused.
I think we forgot to set sshd to start on boot — and if I tell in chroot 
```
# systemctl enable sshd.service
Created symlink sshd.service → (null).
Failed to enable: Too many levels of symbolic links.
```
What can go wrong?
Maybe, need to add fstab?

**Comment by iav** [comment]
Yes!
It works after I add into fstab 
/dev/sda1    /    ext3    defaults  0 1

**Comment by Ft1Byh0hl** [comment]
Sounds like you figured it out.
